### ISSUE TITLE
Методы выделения контуров изображения

### ISSUE THREAD

**Issue by Klimzy** [MADeyneko/image_preparing#1]
Здравствуйте.
Нашел вашу статью на NTA https://newtechaudit.ru/obzor-osnovnyh-algoritmov-vydeleniya-konturov-izobrazheniya/.

Отличная работа. Был бы очень благодарен, если поделитесь кодом реализации остальных операторов.

Заранее спасибо

**Comment by MADeyneko** [comment]
Прошу прощение за задержку. 
Код закоммитил. 

-----------------------------------------------------------------------
С уважением, 
Дейнеко Максим Андреевич
